version = 0.1

[default.deploy.parameters]
stack_name = "Sam-TeleBot-dev-b"
resolve_s3 = true
s3_prefix = "Sam-TeleBot-dev-b"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
